all:
  hosts:
    plutofi-primary:
      ansible_host: 134.209.129.33
      # ansible_user: root
      # ansible_ssh_private_key_file: ~/.ssh/id_rsa
  vars:
    ansible_python_interpreter: /usr/bin/python3
